### ISSUE TITLE
top-nav pages (Better format/UI and content)

### ISSUE THREAD

**Issue by DSchroederOSU** [DSchroederOSU/SeniorCapstone#155]
Parker, I added content to the about and contact pages.

If you want to work on UI beautification and customizing how the header and content components look, that would be great

**Comment by brunip** [comment]
yup sounds good to me

**Comment by jackrwoods** [comment]
Parker, I'm going to talk with my boss and I'll begin adding front-end user stories to the waffle.io page. They'll also show up as issues on github.
