### ISSUE TITLE
top-nav-contact Add Contact information

### ISSUE THREAD

**Issue by brunip** [DSchroederOSU/SeniorCapstone#171]
Get approval from jack to add accurate contact information for Sus Office faculty and update the contact info

**Comment by DSchroederOSU** [comment]
@jackrwoods

**Comment by jackrwoods** [comment]
Would it be possible to only add contact info for Brandon Trelstad and Lety Cavazos? Student employees tend to come and go, and the regular office staff may not be able to update the HTML as necessary.

Let me know if you need their info.
