### ISSUE TITLE
Add duplicate data upload prevention

### ISSUE THREAD

**Issue by jackrwoods** [DSchroederOSU/SeniorCapstone#182]
In case an acquisuite uploads duplicate data, our server should check timestamps to ensure that data received is not a duplicate of previously received data.

**Comment by TheNulls** [comment]
Update on this: 
Currently incoming data is being compared to stored data. However there is an issue with the how mongoose stores a Date type compared to default. Will follow up on this and link commit where this is fixed.

**Comment by TheNulls** [comment]
Changed the way the data is stored which made it much easier for duplicate detection/prevention. Marking this as resolved.
