### ISSUE TITLE
Create Acquisuites table

### ISSUE THREAD

**Issue by jackrwoods** [DSchroederOSU/SeniorCapstone#203]
This will allow users to add/remove an acquisuite to/from a building.

**Comment by TheNulls** [comment]
My current thoughts for this is to create a Meter table that contains all unassigned meters. This would make it easy to display which meters are unassigned.

When an unassigned meter gets added to a building, it would remove the meter from the Meter table. When a meter is removed from a building, it will get pushed to the Meter table.  While this would increase the number of DB calls our application makes, it would be much safer, in terms of data loss, than keeping it store locally in a variable array. I will experiment with this functionality soon and update issue as appropriate.

**Comment by TheNulls** [comment]
Above solution was needlessly convoluted when I tried it out. There was a lot of nested database calls. To simplify, I added a meters array in the building schema. When a meter is added/removed to a building, it will just simply be pushed/popped appropriately. Once implementation is done, this issue will be resolved.

**Comment by TheNulls** [comment]
Disregard above post. It was actually much simpler than I thought. It still works as a reference with same functionality mentioned above.

TODO:
-Create Edit Building where we can add/remove meters

**Comment by TheNulls** [comment]
Edit Building has been roughly implemented. Currently set up to be able to easily removed from buildings, but ability to add back needs added still.

**Comment by TheNulls** [comment]
This has been complete when 'editBuilding' was implemented fully. Closing issue.
